const SAMPLE_URLS={kick:"samples/kickdrum.wav",snare:"samples/snare.wav",closed_hihat:"samples/closed_hihat.wav",open_hihat:"samples/open_hihat.wav",crash:"samples/crash.wav",ride:"samples/ride.wav",clap:"samples/clap.wav",tom_high:"samples/tom_high.wav",tom_low:"samples/tom_low.wav"};
const PAD_DEFS=[["A","kick","Kick"],["S","snare","Snare"],["D","snare","Snare"],["F","closed_hihat","Closed HH"],["G","closed_hihat","Closed HH"],["H","open_hihat","Open HH"],["J","crash","Crash"],["K","ride","Ride"],["L","clap","Clap"],["Z","clap","Clap"],["X","tom_high","High Tom"],["C","tom_low","Low Tom"]];
const ROWS=["kick","snare","closed_hihat","open_hihat","crash","ride","clap","tom_high","tom_low"];
const NAMES={kick:"Kick",snare:"Snare",closed_hihat:"Closed HH",open_hihat:"Open HH",crash:"Crash",ride:"Ride",clap:"Clap",tom_high:"High Tom",tom_low:"Low Tom"};
const DEFAULT_PAD=Object.fromEntries(PAD_DEFS.map(([k,p])=>[k,p]));
const DEFAULT_CTRL={r:"record", " ":"playStop",t:"overdub","escape":"stop","backspace":"clear","m":"metronome"};
let padMap=JSON.parse(localStorage.getItem("drumLoopPadMapping")||"null")||DEFAULT_PAD;
let ctrlMap=JSON.parse(localStorage.getItem("drumLoopControlMapping")||"null")||DEFAULT_CTRL;

const audioCtx=new (window.AudioContext||window.webkitAudioContext)();
const buffers={}; const keysDown=new Set(); const lastLive={};
async function loadSamples(){let ok=0;for(const [name,url] of Object.entries(SAMPLE_URLS)){try{const r=await fetch(url);if(!r.ok)throw Error(r.status);buffers[name]=await audioCtx.decodeAudioData(await r.arrayBuffer());ok++}catch(e){console.warn("Could not load sample:",url,e)}}document.querySelector("#sampleStatus").textContent=`${ok}/${Object.keys(SAMPLE_URLS).length} SAMPLES READY`;}
async function resume(){if(audioCtx.state==="suspended")await audioCtx.resume()}
function playSample(name,fromPlayback=false){const b=buffers[name];if(!b)return;const s=audioCtx.createBufferSource();s.buffer=b;s.connect(audioCtx.destination);s.start()}
function livePad(name,key){const now=performance.now();if(lastLive[key]&&now-lastLive[key]<80)return;lastLive[key]=now;playSample(name,false);document.querySelectorAll(`.pad[data-pad="${name}"]`).forEach(x=>{x.classList.add("hit");setTimeout(()=>x.classList.remove("hit"),80)})}

const loop={slots:Array.from({length:9},()=>({events:[],bpm:120,bars:4})),selected:0,bpm:120,bars:4,quant:16,playing:false,recording:false,overdub:false,metro:false,start:0,frame:0,recordEvents:[],recordStart:0};
const seq={patterns:Array.from({length:9},()=>({steps:16,rows:Object.fromEntries(ROWS.map(r=>[r,Array(16).fill(false)]))})),selected:0,bpm:150,steps:16,swing:0,quant:16,metro:false,playing:false,playAll:false,start:0,frame:0,prevStep:-1,muted:new Set()};

const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function loopDuration(){return loop.bars*4*60/loop.bpm}
function stopOther(mode){if(mode==="loop")seqStop();else loopStopAll()}
function loopStopAll(){loop.playing=false;loop.recording=false;loop.overdub=false;cancelAnimationFrame(loop.frame);$("#loopPlayhead").style.display="none";$("#loopTransportState").textContent="STOPPED";$("#loopModeState").textContent="READY"}
function loopStart(){stopOther("loop");loop.playing=true;loop.start=audioCtx.currentTime;$("#loopTransportState").textContent="PLAYING";scheduleLoopFrame()}
function loopRecord(){stopOther("loop");loop.recording=true;loop.playing=true;loop.overdub=false;loop.recordEvents=[];loop.recordStart=performance.now();loop.start=audioCtx.currentTime;$("#loopTransportState").textContent="RECORDING";scheduleLoopFrame()}
function loopOverdub(){const s=loop.slots[loop.selected];if(!s.events.length)return;stopOther("loop");loop.overdub=true;loop.playing=true;loop.start=audioCtx.currentTime;loop.recordStart=performance.now();$("#loopTransportState").textContent="OVERDUB";scheduleLoopFrame()}
function quantizeTime(t){if(!loop.quant)return t;const grid=60/loop.bpm*(4/loop.quant);return Math.round(t/grid)*grid}
function recordPad(pad){if(!loop.recording&&!loop.overdub)return;const t=quantizeTime((performance.now()-loop.recordStart)/1000);if(t<=loopDuration())loop.recordEvents.push({time:t,pad})}
function finishRecord(){const s=loop.slots[loop.selected];const events=loop.recordEvents.slice();if(loop.overdub)s.events=s.events.concat(events).sort((a,b)=>a.time-b.time);else s.events=events;s.bpm=loop.bpm;s.bars=loop.bars;loop.recording=false;loop.overdub=false;loop.playing=true;loop.start=audioCtx.currentTime;renderLoopSlots();renderTimeline();$("#loopTransportState").textContent="PLAYING"}
function scheduleLoopFrame(){cancelAnimationFrame(loop.frame);const tick=()=>{if(!loop.playing)return;const dur=loopDuration();const pos=(audioCtx.currentTime-loop.start)%dur;$("#loopPlayhead").style.left=(pos/dur*100)+"%";$("#loopPlayhead").style.display="block";$("#loopPosition").textContent=`${pos.toFixed(2)} / ${dur.toFixed(2)} s`;if(loop.recording||loop.overdub){if((performance.now()-loop.recordStart)/1000>=dur)finishRecord()}const s=loop.slots[loop.selected];if(!loop.recording&&s.events.length){for(const e of s.events){const prev=(pos-(1/60));if(e.time>=Math.max(0,prev)&&e.time<pos)playSample(e.pad,true)}}loop.frame=requestAnimationFrame(tick)};loop.frame=requestAnimationFrame(tick)}
function selectLoop(i){loop.selected=i;renderLoopSlots();renderTimeline()}
function renderLoopSlots(){$("#loopSlots").innerHTML=loop.slots.map((s,i)=>`<button class="slot ${i===loop.selected?"selected":""} ${s.events.length?"recorded":""}" data-i="${i}">${i+1}<br><small>${s.events.length?s.events.length+" hits":"EMPTY"}</small></button>`).join("");$$(".slot").forEach(b=>b.onclick=()=>selectLoop(+b.dataset.i))}
function renderTimeline(){const s=loop.slots[loop.selected],dur=loopDuration();$("#loopEvents").innerHTML=s.events.map(e=>`<i class="event-dot" style="left:${Math.min(100,e.time/dur*100)}%" title="${NAMES[e.pad]||e.pad}"></i>`).join("");$("#loopPosition").textContent=`0.00 / ${dur.toFixed(2)} s`}
function clearLoop(i=loop.selected){loop.slots[i].events=[];if(loop.recording&&i===loop.selected)loop.recordEvents=[];renderLoopSlots();renderTimeline()}
function clearAllLoops(){loop.slots.forEach(s=>s.events=[]);renderLoopSlots();renderTimeline()}

function seqStop(){seq.playing=false;seq.playAll=false;cancelAnimationFrame(seq.frame);seq.prevStep=-1;$$(".cell.current").forEach(c=>c.classList.remove("current"));$("#seqTransportState").textContent="STOPPED"}
function seqStart(all=false){stopOther("seq");seq.playing=true;seq.playAll=all;seq.start=audioCtx.currentTime;seq.prevStep=-1;$("#seqTransportState").textContent=all?"PLAY ALL":"PLAYING";scheduleSeqFrame()}
function stepDuration(){return 60/seq.bpm/4}
function scheduleSeqFrame(){cancelAnimationFrame(seq.frame);const tick=()=>{if(!seq.playing)return;const elapsed=audioCtx.currentTime-seq.start;let step=Math.floor(elapsed/stepDuration())%seq.steps;const cells=$$(".cell.current");cells.forEach(c=>c.classList.remove("current"));$$(`.cell[data-step="${step}"]`).forEach(c=>c.classList.add("current"));if(step!==seq.prevStep){if(step===0&&seq.playAll){seq.selected=(seq.selected+1)%9;renderSeqGrid()}const p=seq.patterns[seq.selected];ROWS.forEach(r=>{if(p.rows[r][step]&&!seq.muted.has(r))playSample(r,true)});if(seq.metro&&step%4===0)metronomeClick(step===0)}seq.prevStep=step;seq.frame=requestAnimationFrame(tick)};seq.frame=requestAnimationFrame(tick)}
function metronomeClick(accent=false){const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.frequency.value=accent?1200:800;g.gain.setValueAtTime(.08,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.05);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.06)}
function renderSeqSlots(){$("#seqSlots").innerHTML=seq.patterns.map((p,i)=>`<button class="slot ${i===seq.selected?"selected":""}" data-i="${i}">P${i+1}<br><small>${p.steps} STEPS</small></button>`).join("");$$("#seqSlots .slot").forEach(b=>b.onclick=()=>{seq.selected=+b.dataset.i;renderSeqSlots();renderSeqGrid()})}
function renderSeqGrid(){const p=seq.patterns[seq.selected];$("#seqGrid").innerHTML=ROWS.map(r=>`<div class="seq-row"><div class="row-label"><button class="mute ${seq.muted.has(r)?"active":""}" data-mute="${r}">M</button>${NAMES[r]}</div>${Array.from({length:p.steps},(_,i)=>`<button class="cell ${p.rows[r][i]?"on":""}" data-row="${r}" data-step="${i}"></button>`).join("")}</div>`).join("");$$(".cell").forEach(c=>c.onclick=()=>{const r=c.dataset.row,i=+c.dataset.step;p.rows[r][i]=!p.rows[r][i];c.classList.toggle("on",p.rows[r][i]);if(p.rows[r][i])playSample(r)});$$(".mute").forEach(b=>b.onclick=()=>{const r=b.dataset.mute;seq.muted.has(r)?seq.muted.delete(r):seq.muted.add(r);renderSeqGrid()})}
function clearSeq(){const p=seq.patterns[seq.selected];p.rows=Object.fromEntries(ROWS.map(r=>[r,Array(p.steps).fill(false)]));renderSeqGrid()}
function fillHH(){const p=seq.patterns[seq.selected];for(let i=0;i<p.steps;i+=2)p.rows.closed_hihat[i]=true;renderSeqGrid()}
function randomize(){const p=seq.patterns[seq.selected];ROWS.forEach(r=>p.rows[r]=p.rows[r].map(()=>Math.random()<.22));renderSeqGrid()}

function renderPads(){const current={};Object.entries(padMap).forEach(([k,p])=>{current[p]??=[];current[p].push(k.toUpperCase())});$("#pads").innerHTML=ROWS.map(p=>{const key=(current[p]||[])[0]||"—";return `<button class="pad" data-pad="${p}"><kbd>${key}</kbd><strong>${NAMES[p]}</strong></button>`}).join("");$$(".pad").forEach(b=>b.onclick=async()=>{await resume();livePad(b.dataset.pad,"mouse");recordPad(b.dataset.pad)})}
function normalizeKey(e){return e.key.length===1?e.key.toLowerCase():e.key.toLowerCase()}
function handleControl(c){if(c==="record")loopRecord();if(c==="playStop")loop.playing?loopStopAll():loopStart();if(c==="overdub")loopOverdub();if(c==="stop")loopStopAll();if(c==="clear")clearLoop();if(c==="metronome"){loop.metro=!loop.metro;$("#loopMetro").textContent=`METRO ${loop.metro?"ON":"OFF"}`}}
document.addEventListener("keydown",async e=>{await resume();if(e.repeat)return;const k=normalizeKey(e);if($("#mappingDialog").open){if(e.target.classList.contains("map-key"))return;return}if(/^[1-9]$/.test(k)){const i=+k-1;if(e.shiftKey){if(activeMode==="loop")clearLoop(i);else seq.patterns[i].rows=Object.fromEntries(ROWS.map(r=>[r,Array(seq.patterns[i].steps).fill(false)]));renderSeqSlots();renderSeqGrid()}else{if(activeMode==="loop")selectLoop(i);else{seq.selected=i;renderSeqSlots();renderSeqGrid();seqStart(false)}}e.preventDefault();return}if(e.key==="Escape"){if(activeMode==="loop")loopStopAll();else seqStop();return}if(e.key==="Backspace"){if(activeMode==="loop")clearLoop();return}if(ctrlMap[k]&&activeMode==="loop"){handleControl(ctrlMap[k]);e.preventDefault();return}if(padMap[k]&&!keysDown.has(k)){keysDown.add(k);livePad(padMap[k],k);recordPad(padMap[k]);e.preventDefault()}});document.addEventListener("keyup",e=>keysDown.delete(normalizeKey(e)));

let activeMode="loop";
$$(".mode-tab").forEach(b=>b.onclick=()=>{const m=b.dataset.mode;if(m===activeMode)return;if(m==="loop")seqStop();else loopStopAll();activeMode=m;$$(".mode-tab").forEach(x=>x.classList.toggle("active",x===b));$("#loopMode").classList.toggle("hidden",m!=="loop");$("#seqMode").classList.toggle("hidden",m!=="seq")});

$("#loopRecord").onclick=loopRecord;$("#loopPlay").onclick=()=>loop.playing?loopStopAll():loopStart();$("#loopOverdub").onclick=loopOverdub;$("#loopStop").onclick=loopStopAll;$("#loopClear").onclick=()=>clearLoop();$("#loopClearAll").onclick=clearAllLoops;
$("#loopBpm").oninput=e=>{loop.bpm=Math.max(60,Math.min(180,+e.target.value||120));renderTimeline()};$("#loopBars").onchange=e=>{loop.bars=+e.target.value;renderTimeline()};$("#loopQuant").onchange=e=>loop.quant=+e.target.value;$("#loopMetro").onclick=()=>{loop.metro=!loop.metro;$("#loopMetro").textContent=`METRO ${loop.metro?"ON":"OFF"}`};
$("#seqBpm").oninput=e=>seq.bpm=Math.max(60,Math.min(200,+e.target.value||150));$("#seqSteps").onchange=e=>{seq.steps=+e.target.value;const p=seq.patterns[seq.selected];ROWS.forEach(r=>p.rows[r]=p.rows[r].slice(0,seq.steps).concat(Array(Math.max(0,seq.steps-p.rows[r].length)).fill(false)));p.steps=seq.steps;renderSeqGrid();renderSeqSlots()};$("#seqSwing").oninput=e=>{$("#seqSwingOut").textContent=e.target.value+"%";seq.swing=+e.target.value};$("#seqQuant").onchange=e=>seq.quant=+e.target.value;$("#seqMetro").onclick=()=>{seq.metro=!seq.metro;$("#seqMetro").textContent=`METRO ${seq.metro?"ON":"OFF"}`};
$("#seqPlay").onclick=()=>seq.playing?seqStop():seqStart(false);$("#seqPlayAll").onclick=()=>seqStart(true);$("#seqStop").onclick=seqStop;$("#seqClear").onclick=clearSeq;$("#seqFill").onclick=fillHH;$("#seqRandom").onclick=randomize;

function renderMappings(){const pd=Object.entries(padMap).map(([k,p])=>`<div class="mapping-item"><span>${NAMES[p]||p}</span><button type="button" class="map-key" data-type="pad" data-name="${p}">${k.toUpperCase()}</button></div>`).join("");$("#padMappings").innerHTML=pd;const names={record:"Record","playStop":"Play / Stop",overdub:"Overdub",stop:"Stop",clear:"Clear Selected",metronome:"Metronome"};$("#controlMappings").innerHTML=Object.entries(ctrlMap).map(([k,c])=>`<div class="mapping-item"><span>${names[c]}</span><button type="button" class="map-key" data-type="ctrl" data-name="${c}">${k===" "?"SPACE":k.toUpperCase()}</button></div>`).join("");$$(".map-key").forEach(b=>b.onclick=()=>captureMapping(b))}
function captureMapping(btn){btn.classList.add("capture");const fn=e=>{e.preventDefault();const key=normalizeKey(e);const target=btn.dataset.name;if(btn.dataset.type==="pad"){Object.keys(padMap).forEach(k=>{if(padMap[k]===target)delete padMap[k]});padMap[key]=target;localStorage.setItem("drumLoopPadMapping",JSON.stringify(padMap))}else{Object.keys(ctrlMap).forEach(k=>{if(ctrlMap[k]===target)delete ctrlMap[k]});ctrlMap[key]=target;localStorage.setItem("drumLoopControlMapping",JSON.stringify(ctrlMap))}btn.classList.remove("capture");document.removeEventListener("keydown",fn,true);renderPads();renderMappings()};document.addEventListener("keydown",fn,true)}
$("#mappingBtn").onclick=()=>{$("#mappingDialog").showModal();renderMappings()};$("#restoreMappings").onclick=()=>{padMap={...DEFAULT_PAD};ctrlMap={...DEFAULT_CTRL};localStorage.setItem("drumLoopPadMapping",JSON.stringify(padMap));localStorage.setItem("drumLoopControlMapping",JSON.stringify(ctrlMap));renderPads();renderMappings()};$("#clearMappings").onclick=()=>{padMap={};ctrlMap={};localStorage.setItem("drumLoopPadMapping","{}");localStorage.setItem("drumLoopControlMapping","{}");renderPads();renderMappings()};

renderPads();renderLoopSlots();renderTimeline();renderSeqSlots();renderSeqGrid();loadSamples();
